services:
  auth_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=auth_admin
      - POSTGRES_PASSWORD=auth_admin
      - DB_NAME=authdb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/data/:/var/lib/postgresql/data
