services:
  auth_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=auth_admin
      - POSTGRES_PASSWORD=auth_admin
      - POSTGRES_DB=authdb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/data/:/var/lib/postgresql/data
  auth_redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
